name: inner-product

on: [push, pull_request, workflow_dispatch]

jobs:
  inner-product:
    runs-on: ubuntu-latest
    env:
      path: homework/inner-product/build
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: Create build directory
      run: mkdir ${{ env.path }}
    - name: Compile
      working-directory: ${{ env.path }}
      run: |
        cmake ..
        make
    - name: Run tests
      working-directory: ${{ env.path }}
      run: ctest -V